# Generated by Django 3.1.7 on 2021-03-24 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mots', models.TextField()),
                ('niveau', models.CharField(max_length=40)),
                ('id_in_base', models.IntegerField(blank=True)),
            ],
            options={
                'db_table': 'mots',
            },
        ),
        migrations.CreateModel(
            name='num_publis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_revue', models.IntegerField()),
                ('id_numero', models.IntegerField()),
                ('type', models.IntegerField()),
                ('titre', models.TextField()),
                ('soustitre', models.TextField()),
                ('position', models.IntegerField()),
                ('resume', models.TextField()),
                ('article', models.TextField()),
                ('id_ecriture_parent', models.IntegerField()),
                ('slug', models.CharField(max_length=40)),
                ('date_publication', models.IntegerField()),
                ('valid', models.IntegerField()),
            ],
            options={
                'db_table': 'num_publis',
            },
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_relation', models.CharField(max_length=40)),
                ('id_predecesseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predecesseur', to='graph.mots')),
                ('id_sucesseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucesseur', to='graph.mots')),
            ],
            options={
                'db_table': 'relation',
            },
        ),
        migrations.CreateModel(
            name='num_auteurs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.CharField(max_length=40)),
                ('position', models.IntegerField()),
                ('valid', models.IntegerField()),
                ('id_publi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graph.num_publis')),
            ],
            options={
                'db_table': 'num_auteurs',
            },
        ),
    ]
